version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - .:/app
    env_file:
      - .env  
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge