version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: candidate_selection_api
    volumes:
      - .:/app
    env_file:
      - .env  
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    # Optional: remove command, so Dockerfile CMD is used
    # OR match correct module path:
    command: uvicorn src.candidate_selection.web.app:app --host 0.0.0.0 --port 8001 --reload

networks:
  app-network:
    driver: bridge
